PORT = 7777
EXCHANGE = 'Q'
MONGO_USERNAME = 'test'
MONGO_PASSWORD = 'test'
MONGO_SERVER = 'localhost'
MONGO_PORT = '27017'
MONGO_DATABASE = 'Q'
MONGO_CONNECTION_STRING = 'mongodb://'+MONGO_USERNAME+':'+MONGO_PASSWORD+'@'+MONGO_SERVER+':'+MONGO_PORT+'/'+MONGO_DATABASE
